blank_issues_enabled: false
contact_links:
  - name: Atlas Discussions
    url: https://github.com/orgs/atlas/discussions/categories/android
    about: Please ask and answer questions here.
  - name: Atlas Website
    url: https://atlas.org/
    about: Docs and other ways to contact us here.



